/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package groupproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Admin
 */
public class AcctP extends javax.swing.JFrame {

   Connection con;
  PreparedStatement ps;
  Statement st;
    public AcctP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRegister1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtNames1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblStudNo = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblConPass = new javax.swing.JLabel();
        txtConPass = new javax.swing.JPasswordField();
        lblCon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setText("CREATE NEW ACCOUNT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 470, 56));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Contact No");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 205, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Work ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 205, -1));

        txtContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactKeyReleased(evt);
            }
        });
        jPanel2.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 500, -1));

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 500, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back >>");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 250, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 170, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Full Names");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 243, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1269, 212, 132, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1279, 222, 132, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1289, 232, 95, -1));

        btnRegister1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister1.setText("Register");
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 250, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 127, 243, -1));

        txtNames1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNames1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNames1KeyReleased(evt);
            }
        });
        jPanel2.add(txtNames1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 500, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 205, -1));

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 500, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("New Password");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 205, -1));

        lblName.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 500, -1));

        lblStudNo.setBackground(new java.awt.Color(255, 51, 0));
        jPanel2.add(lblStudNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 500, -1));

        lblPhone.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 500, -1));

        lblPass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 500, -1));

        lblConPass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 500, -1));

        txtConPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConPassKeyReleased(evt);
            }
        });
        jPanel2.add(txtConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 382, 500, 30));

        lblCon.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\software Eng\\test\\OIP (1)3.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyReleased

        String input = txtContact.getText().trim();
        if (!input.matches("\\d{10}")) {
            // Input does not contain exactly 10 digits
            if (input.matches("\\D+")) {
                // Input contains non-digits
                lblPhone.setText("Contact number must contain only digits.");
            } else {
                // Input contains digits but not 10 of them
                lblPhone.setText("Contact number must contain exactly 10 digits.");
            }
            lblPhone.setForeground(Color.RED);
            txtContact.setBackground(Color.WHITE);
        } else {
            // Input is a valid 10-digit number
            lblPhone.setText("");
            txtContact.setBackground(Color.GREEN);
        }

    }//GEN-LAST:event_txtContactKeyReleased

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased

        String input = txtID.getText().trim();
        if (!input.matches("\\d{4}")) {
            // Input does not contain exactly 9 digits
            if (input.matches("\\D+")) {
                // Input contains non-digits
                lblStudNo.setText("work number must contain only digits.");
            } else {
                // Input contains digits but not 9 of them
                lblStudNo.setText("work number must contain exactly 4 digits.");
            }
            lblStudNo.setForeground(Color.RED);
            txtID.setBackground(Color.WHITE);
        } else {
            // Input is a valid 9-digit number
            lblStudNo.setText("");
            txtID.setBackground(Color.GREEN);
        }

    }//GEN-LAST:event_txtIDKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Login SignUpFrame= new Login();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        txtNames1.setText(null);
        txtID.setText(null);
        txtContact.setText(null);
        txtPass.setText(null);
        txtConPass.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed

        connection();

    }//GEN-LAST:event_btnRegister1ActionPerformed

    private void txtNames1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNames1KeyReleased
        String input = txtNames1.getText().trim();
        if (input.matches("\\d+")) {
            // Input contains only digits, display error message
            lblName.setText("Please enter a valid name no numbers allowed");
            lblName.setForeground(Color.RED);
            txtNames1.setBackground(Color.WHITE);
        } else {
            // Input contains only letters, set text field to green
            lblName.setText("");
            lblName.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_txtNames1KeyReleased

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        String password = String.valueOf(txtPass.getPassword());
        if (password.matches("^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]+$")) {
            if (password.length() >= 8) {
                lblPass.setText("Strong Password");
                lblPass.setForeground(Color.GREEN);
                txtPass.setBackground(Color.GREEN);
            } else {
                lblPass.setText("Medium Password");
                lblPass.setForeground(Color.YELLOW);
                txtPass.setBackground(Color.YELLOW);
            }
        } else {
            lblPass.setText("Weak Password");
            lblPass.setForeground(Color.RED);
            txtPass.setBackground(Color.WHITE);
        }

    }//GEN-LAST:event_txtPassKeyReleased

    private void txtConPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPassKeyReleased

    }//GEN-LAST:event_txtConPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcctP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcctP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcctP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcctP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcctP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRegister1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblConPass;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblStudNo;
    private javax.swing.JPasswordField txtConPass;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNames1;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

    private void connection() {
          
       String Details = txtNames1.getText().toString();
      String Id = txtID.getText().toString();
      String PhoneNo = txtContact.getText().toString();
      String Password = txtPass.getText();
      String Confirm = txtConPass.getText();
     
      
       String  hostname = "jdbc:mysql://localhost:3306/stud";
       String username ="root";
       String passwords="Lethabo27#";

     
       try {
           Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection  con = DriverManager.getConnection(hostname,username,passwords);
                st = con.createStatement();
                
                 if ("".equals(txtNames1.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Full name is required","Error", JOptionPane.ERROR_MESSAGE);
            }
            else if("".equals(txtID.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "work number is required","Error", JOptionPane.ERROR_MESSAGE);
            }
            else if("".equals(txtContact.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Contact number is required","Error", JOptionPane.ERROR_MESSAGE);
}
            else if("".equals(txtPass.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Password is required","Error", JOptionPane.ERROR_MESSAGE);
            }
            else if("".equals(txtConPass.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "confirm password is required","Error", JOptionPane.ERROR_MESSAGE);
            
            
                        
            }else{
                
             Details = txtNames1.getText().toString();
             PhoneNo = txtContact.getText().toString();
             Id = txtID.getText().toString();
             Password = txtPass.getText().toString();
             Confirm =txtConPass.getText().toString();
            
               String default_value = null;
             
             
             String query = "INSERT INTO personnel (Details, PhoneNo, WorkID, Password,ConfirmPass) VALUES ('" + Details + "', '" + PhoneNo + "', '" + Id + "', '" + Password + "', '" + Confirm + "')";
                st.execute(query);
                
                txtNames1.setText("");
                txtContact.setText("");
                txtID.setText("");
                txtPass.setText("");
                txtConPass.setText("");
               
              
                showMessageDialog(null, "Account has been created successfully!");
            }
        
            
         
                 {
              
            }
       } catch (Exception e) {
   System.out.println("Error!" + e.getMessage());
       }
   }

    private int calculatePasswordStrength(String password) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

      }
        
    

