package groupproject;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JRadioButton;

public class Login extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    Statement st;
    ResultSet rs;

    public Login() {
        initComponents();
        JRadioButton personnelRadioButton = new JRadioButton("Personnel");
        ButtonGroup buttonGroup = new ButtonGroup();

        // Add radio button to button group
        buttonGroup.add(personnelRadioButton);

        // Set layout and add components to the frame
        setLayout(new BoxLayout(getContentPane(), BoxLayout.Y_AXIS));
        add(personnelRadioButton);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStud = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnForgot = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stud = new javax.swing.JRadioButton();
        personnel = new javax.swing.JRadioButton();
        tutor = new javax.swing.JRadioButton();
        lblID = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel7.setText("jLabel7");

        jLabel6.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Student No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        txtStud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStudKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStudKeyReleased(evt);
            }
        });
        jPanel1.add(txtStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 480, 40));

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 490, 40));

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister.setText("Sign Up");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 260, -1));

        btnForgot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnForgot.setText("Forgot Password?");
        btnForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotActionPerformed(evt);
            }
        });
        jPanel1.add(btnForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, 20));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 220, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("SOL PLAATJE UNIVERSITY");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        stud.setBackground(new java.awt.Color(255, 255, 255));
        stud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stud.setText("Student");
        stud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studMouseClicked(evt);
            }
        });
        stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studActionPerformed(evt);
            }
        });
        jPanel1.add(stud, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        personnel.setBackground(new java.awt.Color(255, 255, 255));
        personnel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personnel.setText("Personnel");
        personnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personnelMouseClicked(evt);
            }
        });
        personnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personnelActionPerformed(evt);
            }
        });
        jPanel1.add(personnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        tutor.setBackground(new java.awt.Color(255, 255, 255));
        tutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tutor.setText("Tutor");
        jPanel1.add(tutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        lblID.setForeground(new java.awt.Color(255, 51, 0));
        lblID.setText("Fields required");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 480, 10));

        lblPass.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 320, -1));

        lblPassword.setForeground(new java.awt.Color(255, 51, 0));
        lblPassword.setText("Fields required");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 430, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\software Eng\\test\\Screenshot 2024-05-19 101851.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 870, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personnelActionPerformed
       // Close the current main form
        
    }//GEN-LAST:event_personnelActionPerformed

    private void studActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studActionPerformed
      
        
    }//GEN-LAST:event_studActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String studNo = txtStud.getText();
String password = new String(txtPass.getPassword());
String hostname = "jdbc:mysql://localhost:3306/stud";
String usernameDB = "root";
String passwordDB = "Lethabo27#";

// Check if student number and password are provided
if (studNo.isEmpty() || password.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please fill in both Student No and Password");
} else {
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    try {
        // Establish database connection
        con = DriverManager.getConnection(hostname, usernameDB, passwordDB);

        // Prepare SQL statement to check credentials
        String query = "SELECT UserType, Details FROM admin WHERE StudentNo=? AND Passwords=?";
        ps = con.prepareStatement(query);
        ps.setString(1, studNo);
        ps.setString(2, password);
             
        // Execute the query
        rs = ps.executeQuery();

        // Check if the result set contains any rows (i.e., if the user exists with the provided credentials)
        if (rs.next()) {
            // Login successful
            String userType = rs.getString("UserType"); // Retrieve user's role from the database
            String userDetails = rs.getString("Details");

            // Determine which form to open based on the user's role
            if (userType.equals("Student") && stud.isSelected()) {
                JOptionPane.showMessageDialog(this, "Login successful");
                Student studentForm = new Student();
                studentForm.setVisible(true);
                studentForm.pack();
                studentForm.setLocationRelativeTo(null);
                dispose();
                
            } else if (userType.equals("Tutor") && tutor.isSelected()) {
                JOptionPane.showMessageDialog(this, "Login successful");
                Tutor tutorForm = new Tutor();
                tutorForm.setVisible(true);
                tutorForm.pack();
                tutorForm.setLocationRelativeTo(null);
                dispose();
                
            } else {
                JOptionPane.showMessageDialog(this, "Invalid student no or password");
            }
        } else {
            // No rows found, invalid login
            JOptionPane.showMessageDialog(this, "Invalid student no or password");
        }

    } catch (SQLException e) {
        // Handle any SQL errors
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());

    } finally {
        // Close resources
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotActionPerformed
        ForgotPassword ForgotPassFrame = new ForgotPassword();
        ForgotPassFrame.setVisible(true);
        ForgotPassFrame.pack();
        ForgotPassFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnForgotActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        Registration SignUpFrame = new Registration();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        String pass = txtPass.getText();

        if (pass.isEmpty()) {
            lblPassword.setText("Fields required");
        } else {
            lblPassword.setText(""); }
    }//GEN-LAST:event_txtPassKeyReleased

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtStudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudKeyReleased
        // TODO add your handling code here:
        String username = txtStud.getText();

        if (username.isEmpty()) {
            lblID.setText("Fields required");
        } else {
            lblID.setText("");
        }
    }//GEN-LAST:event_txtStudKeyReleased

    private void txtStudKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudKeyPressed

    }//GEN-LAST:event_txtStudKeyPressed

    private void studMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_studMouseClicked

    private void personnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personnelMouseClicked
        PersonnelLogin SignUpFrame = new PersonnelLogin();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_personnelMouseClicked

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgot;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JRadioButton personnel;
    private javax.swing.JRadioButton stud;
    private javax.swing.JRadioButton tutor;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtStud;
    // End of variables declaration//GEN-END:variables

    private void openStudentForm() {

    }
}
